name: Check

on:
  push:
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      buildTool: ${{ steps.filter.outputs.buildTool }}
      todoApp: ${{ steps.filter.outputs.todoApp }}
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            buildTool:
              - 'buildTool/**'
            todoApp:
              - 'todoApp/**'

  buildTool:
    needs: changes
    if: ${{ needs.changes.outputs.buildTool == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 24

      - run: npm ci
        working-directory: buildTool

      - run: npm run check-all
        working-directory: buildTool

  todoApp:
    needs: changes
    if: ${{ needs.changes.outputs.todoApp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 24

      - run: npm ci
        working-directory: todoApp

      - run: npm run check-all
        working-directory: todoApp
